### PR TITLE
Payment id and integrated address support

### PR DESCRIPTION
**Pull request by kirichenko**

### CODE REVIEW

**Comment by frost-monkey** [comment]
I'm very interested in using this code. I'd like to know: is it already running live on a pool somewhere?

Also, thanks a lot for this contribution!

**Comment by kirichenko** [comment]
No, I only tested it on testnet.

**Comment by ghost** [comment]
Hey just curios have you tried the code on a live pool yet and if so are you successful with the implementation

**Comment by kirichenko** [comment]
No, I am not a pool operator. On testnet everything works as needed.

**Comment by bapparabi** [comment]
Its not working in live site ..i have implememted it but i showing minung share for pool devloper not mingi for miner showing share ..so think is not working .. so what qill be the commnad format you use in miner ..

**Comment by ghost** [comment]
Yes we tested on live pool and everything works just not properly. Once the miner starts it is only sending shares to the Developer. The miner gets no shares for themselves any ideas that we could try . this would be a great implementation once it works

**Comment by kirichenko** [comment]
Miner will receive coins from pool only after block maturity will be reached (60 blocks by default).

Try here...
http://monerod.com:8083/#

**Comment by bapparabi** [comment]
Once the miner starts it is only sending shares to the Developer. The miner gets no shares for themselves any ideas that we could try .. this happening when we try to use exchange address ..but when i use normal address it showing correctly 

you just hit your miner to out pool http://drowningpool.net using exchange address and format and see the error you get http://prntscr.com/gl4ytw

**Comment by kirichenko** [comment]
Do you use patched version of pool?
Looks like you don't.

Your pool thinks that you set difficulty after dot "." instead of payment id. My patch solves this also.

**Comment by ghost** [comment]
Ok thanks we will give it a shot

**Comment by kirichenko** [comment]
While pull request is not merged you can try my fork:

```
git clone https://github.com/kirichenko/cryptonote-xmr-pool.git pool_patched
cd pool_patched
npm update
```
Then copy from your current pool these files:
* config.json
* website-example/config.js

And start new pool

**Comment by ghost** [comment]
Link  to the patch  please

**Comment by ghost** [comment]
Thanks again..

On Sep 14, 2017 2:18 PM, "Sergey Kirichenko" <notifications@github.com>
wrote:

While pull request is not merged you can try my fork:

git clone https://github.com/kirichenko/cryptonote-xmr-pool.git pool_patched
cd pool_patched
npm update

Then copy from your current pool these files:

   - config.json
   - website-example/config.js

And start new pool

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/clintar/cryptonote-xmr-pool/pull/14#issuecomment-329582569>,
or mute the thread

**Comment by ghost** [comment]
Great the patch worked is there anyway to get it to allow the rig name and worker ID in there or is that something  may have to come later

**Comment by bapparabi** [comment]
also in admin page i can see Wallet

    Last check: less than a minute ago
    Last status: fail 
"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}

http://prntscr.com/glcg03

is this problem or its ok to keep like that

**Comment by clintar** [comment]
Looks like things are going well with this. I'll try to get some time to look into it tomorrow

**Comment by ghost** [comment]
Thank you thing are working perfect at the moment . you are doing a outstanding job .. keep up the good work

**Comment by kirichenko** [comment]
bapparabi, try to run monero-wallet-rpc with --disable-rpc-login.
Thomasmcdaniel9, the rig name and worker ID - may be some later

**Comment by bapparabi** [comment]
this error we get 

2017-09-15 16:59:06.281     7f0ebbb41780        ERROR   wallet.rpc      src/wallet/wallet_rpc_server.cpp:1849   Must specify --wallet-file or --generate-from-json or --wallet-dir

**Comment by kirichenko** [comment]
Yes  of course, you need to specify --wallet-file and all other required parameters (port, daemon's address, etc). --disable-rpc-login is additional flag.

**Comment by bapparabi** [comment]
Failed to parse arguments: too many positional options have been specified on the command line

i try to pass this commd but not working 

./monero-wallet-rpc --rpc-bind-port 18082 --password-file ~/wallet_pass --wallet-file <wallet name> --disable-rpc-login --trusted-daemon

what is missing or what error 

also when i try to start the rpc i get this error 

./monero-wallet-rpc --rpc-bind-port 18082
Monero 'Helium Hydra' (v0.11.0.0-release)
Logging to ./monero-wallet-rpc.log
2017-09-16 05:59:45.684     7fdff5ff1780        ERROR   wallet.rpc      src/wallet/wallet_rpc_server.cpp:1849   Must specify --wallet-file or --generate-from-json or --wallet-dir

**Comment by kirichenko** [comment]
--wallet-file is empty. It should point to your wallet file

**Comment by bapparabi** [comment]
can provide me the correct command to do this as all comand i try not working

**Comment by kirichenko** [comment]
```
./monero-wallet-rpc --rpc-bind-port 18082 --disable-rpc-login --trusted-daemon --wallet-file wallet/42gctG
```

Wallet file should point to your wallet file.

**Comment by bapparabi** [comment]
Failed to parse arguments: too many positional options have been specified on the command line

**Comment by kirichenko** [comment]
Check carefully command line.

**Comment by appkoders** [comment]
@clintar any reason why this is still not merged with the master?

**Pull request merged**
